### ISSUE TITLE
No /dist

### ISSUE THREAD

**Issue by kodmunki** [maoberlehner/css-selector-extract#48]
v3.3.2 package claims a main of `dist/index.js` but I am not seeing a `dist`. Just me?

**Comment by kodmunki** [comment]
It appears the v3.1.3 does include the `dist` directory and works as expected. The issue that I have it that my project is leveraging `node-sass-magic-importer` which is in turn leveraging `css-selector-extract`, but assuming semver at `^3.1.3`. It appears the `3.2.x` is not backward compatible. Does this project follow a different versioning rules? Am I missing a build step?

**Comment by maoberlehner** [comment]
Im sorry, I messed up. But this should be solved with version 3.3.3 I published an hour ago.

**Comment by kodmunki** [comment]
It doesn't appear to be available on this side of the pond yet. -- I'll post back here once we can grab it and check it out. -- Thanks for the quick reply!!!

**Comment by kodmunki** [comment]
Fixed! Thanks! 👍
